swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/profile/transactions:
    get:
      tags:
        - All Transactions
      summary: All Transactions
      description: API for getting all transactions
      produces:
        - application/json
      responses:
        '200':
          description: Success - Returns all transactions
          schema:
            $ref: '#/definitions/GetAllRes'
        '500':
          description: Internal Server Error

  /user/profile/transactions/{id}:
    get:
      tags:
        - Single Transaction
      summary: Single Transaction
      description: API for getting a single transaction
      parameters:
        - name: id
          in: path
          description: Transaction ID
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Success - Returns the transaction
          schema:
            $ref: '#/definitions/ApiResponse'
        '500':
          description: Internal Server Error

    delete:
      tags:
        - Delete Transaction
      summary: Delete Transaction
      description: API for deleting a transaction
      parameters:
        - name: id
          in: path
          description: Transaction ID
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Success - Transaction deleted successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '500':
          description: Internal Server Error

    put:
      tags:
        - Update Transaction
      summary: Update Transaction
      description: API for updating a transaction
      parameters:
        - name: id
          in: path
          description: Transaction ID
          required: true
          type: string
        - in: body
          name: body
          description: Update Transaction Payload
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: Success - Transaction updated successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '500':
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  GetAllRes:
    type: object
    properties:
      transactions:
        type: array
        items:
          $ref: '#/definitions/UserProfile'